#version: '3'

#services:
#  app:
#    build: .
#    ports:
#      - "3000:3000"
#    environment:
#      - PORT=3000
#      - GEMINI_API_KEY=${GEMINI_API_KEY}
#    volumes:
#      - .:/app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: water_gas_meter
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=AIzaSyDR3ZtQakj23Z-RYLxzJBMENYc48wbMPcQ #put your api key here 
      - PORT=3000 #ports can be changed. set it up according to your computer
      - DB_HOST=mysql
      - DB_PORT=3306 #ports can be changed. set it up according to your computer
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=water_gas_meter
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "tsx", "src/index.ts"]

  mysql:
    image: mysql:8.0
    container_name: water_gas_meter_database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: water_gas_meter
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
